# .github/workflows/first_workflow.yml

name: First Workflow

on: push

jobs:

  first-job:
    name: Name of first step
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run:  echo Hi from our first workflow!

      - uses: actions/checkout@v4

  second-job:
    strategy:
      matrix:
        runtimes: [18, 20, 22]
        os_version: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os_version }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.runtimes }}